name: ingetin_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  animated_bottom_navigation_bar: ^1.4.0
  supabase_flutter: ^2.9.1
  path_provider: ^2.1.5
  intl: ^0.18.1
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/splashAwal.png
    - assets/berandaKosong.png
    - assets/login.png
    - assets/IngetinHitam.png
    - assets/IngetinPutih.png
